version: "3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        restart: always
        env_file:
            - .env
        volumes:
            - ./flask.sqlite:/portfolio-blog/flask.sqlite